#log4j.rootLogger=info, stdout, R
#
#log4j.appender.stdout=org.apache.log4j.ConsoleAppender
#log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#
## Pattern to output the caller's file name and line number.
#log4j.appender.stdout.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n
#
#log4j.appender.R=org.apache.log4j.RollingFileAppender
#log4j.appender.R.File=example.log
#
#log4j.appender.R.MaxFileSize=100KB
## Keep one backup file
#log4j.appender.R.MaxBackupIndex=1
#
#log4j.appender.R.layout=org.apache.log4j.PatternLayout
#log4j.appender.R.layout.ConversionPattern=%p %t %c - %m%n

log4j.rootLogger=INFO, stdout, R, R2, R3

#log4j.appender.stdout.Threshold=WARN
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%t> [%d{yyyy-MM-dd HH:mm:ss}] [%c{1}] [%L line] [%p] %m %n

log4j.appender.R=org.apache.log4j.rolling.RollingFileAppender
log4j.appender.R.ImmediateFlush=true
log4j.appender.R.rollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
#log4j.appender.R.rollingPolicy.ActiveFileName=worker.log
log4j.appender.R.rollingPolicy.FileNamePattern=${catalina.home}/logs/INFO_Log.%d.log
log4j.appender.R.TriggeringPolicy=org.apache.log4j.rolling.SizeBasedTriggeringPolicy
log4j.appender.R.TriggeringPolicy.maxFileSize=100000000
#log4j.appender.R.TriggeringPolicy.MaxFileSize=1KB
#log4j.appender.R.TriggeringPolicy.MaxBackupIndex=5
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%t> [%d{yyyy-MM-dd HH:mm:ss}] [%c{1}] [%L line] [%p] %m %n
log4j.appender.R.filter.filter1=org.apache.log4j.varia.LevelRangeFilter
log4j.appender.R.filter.filter1.LevelMin=INFO
log4j.appender.R.filter.filter1.LevelMax=INFO
log4j.appender.R.filter.filter1.AcceptOnMatch=true
log4j.appender.R.Append=false

log4j.appender.R2=org.apache.log4j.rolling.RollingFileAppender
log4j.appender.R2.ImmediateFlush=true
log4j.appender.R2.rollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
#log4j.appender.R.rollingPolicy.ActiveFileName=worker.log
log4j.appender.R2.rollingPolicy.FileNamePattern=${catalina.home}/logs/WARN_Log.%d.log
log4j.appender.R2.TriggeringPolicy=org.apache.log4j.rolling.SizeBasedTriggeringPolicy
log4j.appender.R2.TriggeringPolicy.MaxFileSize=100000000
#log4j.appender.R2.TriggeringPolicy.MaxBackupIndex=5
log4j.appender.R2.layout=org.apache.log4j.PatternLayout
log4j.appender.R2.layout.ConversionPattern=%t> [%d{yyyy-MM-dd HH:mm:ss}] [%c{1}] [%L line] [%p] %m %n
log4j.appender.R2.filter.filter1=org.apache.log4j.varia.LevelRangeFilter
log4j.appender.R2.filter.filter1.LevelMin=WARN
log4j.appender.R2.filter.filter1.LevelMax=WARN
log4j.appender.R2.filter.filter1.AcceptOnMatch=true
log4j.appender.R2.Append=false

log4j.appender.R3=org.apache.log4j.rolling.RollingFileAppender
log4j.appender.R3.ImmediateFlush=true
#log4j.appender.R3.threshold=error
log4j.appender.R3.rollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
#log4j.appender.R.rollingPolicy.ActiveFileName=worker.log
log4j.appender.R3.rollingPolicy.FileNamePattern=${catalina.home}/logs/ERROR_Log.%d.log
log4j.appender.R3.TriggeringPolicy=org.apache.log4j.rolling.SizeBasedTriggeringPolicy
log4j.appender.R3.TriggeringPolicy.MaxFileSize=100000000
#log4j.appender.R3.TriggeringPolicy.MaxBackupIndex=5
log4j.appender.R3.layout=org.apache.log4j.PatternLayout
log4j.appender.R3.layout.ConversionPattern=%t> [%d{yyyy-MM-dd HH:mm:ss}] [%c{1}] [%L line] [%p] %m %n
log4j.appender.R3.filter.filter1=org.apache.log4j.varia.LevelRangeFilter
log4j.appender.R3.filter.filter1.LevelMin=ERROR
log4j.appender.R3.filter.filter1.LevelMax=FATAL
log4j.appender.R3.filter.filter1.AcceptOnMatch=true
log4j.appender.R3.Append=false
