jdbc.driverClassName=com.mysql.jdbc.Driver


#testDB
#jdbc.url=jdbc:mysql://192.168.1.19:3306/xlabeller?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#jdbc.username=xiilab
#jdbc.password=xiirocks


#testDB2
jdbc.url=jdbc:mysql://192.168.4.2:3306/xlabeller_jhsa?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
jdbc.username=xiilab
jdbc.password=xiirocks

#realDB
#jdbc.url=jdbc:mysql://172.17.0.1:33066/xlabeller?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#jdbc.username=xlabeller
#jdbc.password=xlabeller!@


#localDB
#jdbc.url=jdbc:mysql://localhost:3306/xlabeller?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#jdbc.username=xiilab
#jdbc.password=xiirocks