jdbc.driverClassName=com.mysql.jdbc.Driver


#testDB
#jdbc.url=jdbc:mysql://192.168.4.2:33066/xlabeller_juno1?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#jdbc.username=xiilab
#jdbc.password=xiirocks


##testDB2
jdbc.url=jdbc:mysql://192.168.4.2:3306/xlabeller_juno2?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
jdbc.username=xiilab
jdbc.password=xiirocks

#testDB3
#jdbc.url=jdbc:mysql://192.168.2.52:33066/xlabeller?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#jdbc.username=xlabeller
#jdbc.password=xlabeller!@

#realDB
#jdbc.url=jdbc:mysql://172.17.0.1:33066/xlabeller?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
##jdbc.url=jdbc:mysql://192.168.4.11:33066/xlabeller?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#jdbc.username=xlabeller
#jdbc.password=xlabeller!@


#localDB
#jdbc.url=jdbc:mysql://localhost:3306/xlabeller?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#jdbc.username=root
#jdbc.password=xiirocks
